apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: face-recognition-serve
  annotations:
    scenarios.ai.sap.com/description: "Face recognition"
    scenarios.ai.sap.com/name: "face-recognition"
    executables.ai.sap.com/description: "Face recognition serving executable"
    executables.ai.sap.com/name: "face-recognition-executable"
  labels:
    scenarios.ai.sap.com/id: "face-recognition"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
    - name: facialRecognitionModel
  template:
    apiVersion: serving.kserve.io/v1beta1
    metadata:
      labels: |
        ai.sap.com/resourcePlan: infer.l
    spec: |
      predictor:
        imagePullSecrets:
        - name: credsyk
        containers:
        - name: kfserving-container
          image: "docker.io/yeekhee/facial-recognition-serve:01"
          ports:
          - containerPort: 9001
            protocol: TCP
          command: ["/bin/sh", "-c"]
          env:
          - name: MODEL_LOCATION
            value: "{{inputs.artifacts.facialRecognitionModel}}"
          - name: ENCODINGS_FILE
            value: "/app/model/encodings.pkl"
