apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: facial-recog-pipeline # executable id, must be unique across all your workflows (YAML files)
  annotations:
    scenarios.ai.sap.com/description: "Add Facial Recognition code to AI Core"
    scenarios.ai.sap.com/name: "Facial-Recognition" # Scenario name should be the use case
    executables.ai.sap.com/description: "Train with image data"
    executables.ai.sap.com/name: "training" # Executable name should describe the workflow in the use case
    artifacts.ai.sap.com/housedataset.kind: "dataset" # Helps in suggesting the kind of inputs that can be attached.
  labels:
    scenarios.ai.sap.com/id: "facial-recognition-dataline"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: credsyk # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    metadata:
        labels:
            ai.sap.com/resourcePlan: starter
    # inputs:
    #   artifacts:  # placeholder for cloud storage attachements
    #     - name: facialrecognition # a name for the placeholder
    #       path: /app/data/ # where to copy in the Dataset in the Docker image
    container:
      image: docker.io/yeekhee/facial-recognition-test:01 # Your docker image name
      command: ["/bin/sh", "-c"]
      # env:
      #   - name: DT_MAX_DEPTH # name of the environment variable inside Docker container
      #     value: "3" # will make it as variable later
      args:
        - "python /app/src/main.py"
